### ISSUE TITLE
UrlTokenBindings - not part of rich_http_server package

### ISSUE THREAD

**Issue by inetBrad** [sidoh/rich_http_server#4]
Seems this snippet of code is part of other projects, but not in the rich_http_server package. The stand-alone example fails to compile using Arduino 1.8.21. If there is a dependency to another repo, maybe add a link to the readme?

**Comment by janhajk** [comment]
Use this:
https://github.com/sidoh/path_variable_handlers

**Comment by sidoh** [comment]
Merged this guy which hopefully prevents this from popping up https://github.com/sidoh/rich_http_server/pull/5
