### ISSUE TITLE
marked 'override', but does not override

### ISSUE THREAD

**Issue by Chilled** [sidoh/rich_http_server#6]
Having some issue compiling a project I want to try (https://github.com/kwerner72/espfancontrol) and there are also the same errors in your sample code. This is what I got (Arduino IDE 1.8.16 / MacOS / NodeMCU 1.0)

`Arduino: 1.8.16 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 460800"

In file included from /Users/sven/SynologyDrive/Making/Arduino/libraries/RichHttpServer/src/Platforms/PlatformESP32.h:4,
                 from /Users/sven/SynologyDrive/Making/Arduino/libraries/RichHttpServer/src/RichHttpServer.h:10,
                 from /Users/sven/Documents/GitHub/espfancontrol/fan_control/fan_control.ino:10:
/Users/sven/SynologyDrive/Making/Arduino/libraries/RichHttpServer/src/Platforms/PlatformEspressif.h: In instantiation of 'class RichHttp::Generics::EspressifRequestHandler<RichHttp::Generics::Configs::ESP8266Config>':
/Users/sven/SynologyDrive/Making/Arduino/libraries/RichHttpServer/src/Platforms/PlatformESP8266.h:28:42:   required from here
/Users/sven/SynologyDrive/Making/Arduino/libraries/RichHttpServer/src/Platforms/PlatformEspressif.h:76:22: error: 'bool RichHttp::Generics::EspressifRequestHandler<TConfig>::canHandle(typename TConfig::HttpMethod, String) [with TConfig = RichHttp::Generics::Configs::ESP8266Config; typename TConfig::HttpMethod = HTTPMethod]' marked 'override', but does not override
   76 |         virtual bool canHandle(typename TConfig::HttpMethod method, String uri) override {
      |                      ^~~~~~~~~
/Users/sven/SynologyDrive/Making/Arduino/libraries/RichHttpServer/src/Platforms/PlatformEspressif.h:80:22: error: 'bool RichHttp::Generics::EspressifRequestHandler<TConfig>::canUpload(String) [with TConfig = RichHttp::Generics::Configs::ESP8266Config]' marked 'override', but does not override
   80 |         virtual bool canUpload(String uri) override {
      |                      ^~~~~~~~~
/Users/sven/SynologyDrive/Making/Arduino/libraries/RichHttpServer/src/Platforms/PlatformEspressif.h:84:22: error: 'bool RichHttp::Generics::EspressifRequestHandler<TConfig>::handle(typename TConfig::ServerType&, typename TConfig::HttpMethod, String) [with TConfig = RichHttp::Generics::Configs::ESP8266Config; typename TConfig::ServerType = esp8266webserver::ESP8266WebServerTemplate<WiFiServer>; typename TConfig::HttpMethod = HTTPMethod]' marked 'override', but does not override
   84 |         virtual bool handle(typename TConfig::ServerType& server, typename TConfig::HttpMethod method, String uri) override {
      |                      ^~~~~~
/Users/sven/SynologyDrive/Making/Arduino/libraries/RichHttpServer/src/Platforms/PlatformEspressif.h:106:22: error: 'void RichHttp::Generics::EspressifRequestHandler<TConfig>::upload(typename TConfig::ServerType&, String, HTTPUpload&) [with TConfig = RichHttp::Generics::Configs::ESP8266Config; typename TConfig::ServerType = esp8266webserver::ESP8266WebServerTemplate<WiFiServer>]' marked 'override', but does not override
  106 |         virtual void upload(typename TConfig::ServerType& server, String uri, HTTPUpload& upload) override {
      |                      ^~~~~~
exit status 1
Fehler beim Kompilieren für das Board NodeMCU 1.0 (ESP-12E Module).

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.
`

**Comment by sidoh** [comment]
Should be fixed!
